name: apple_market_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  get_it: ^8.0.3
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.3
  json_serializable: ^6.9.4


flutter:

  uses-material-design: true


  assets:
    - asset/
    - asset/image/

